apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-srv
spec:
  selector:
    app: postgres-depl
  ports:
    - port: 5432
      targetPort: 5432
      name: db
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
spec:
  selector:
    matchLabels:
      app: postgres-depl
  template:
    metadata:
      labels:
        app: postgres-depl
    spec:
      containers:
        - name: postgres-depl
          image: postgres:17-alpine
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POSTGRES_DB
              value: "testDB"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgres-storage
              mountPath: /postgres-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-srv
spec:
  selector:
    app: adminer-depl
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-depl
spec:
  selector:
    matchLabels:
      app: adminer-depl
  template:
    metadata:
      labels:
        app: adminer-depl
    spec:
      containers:
        - name: adminer-depl
          image: adminer
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
